app/index.html, app/scripts/app.js
Adds onMenuSelect so the left sidebar menu closes after selecting a
menu item when drawerPanel is narrow.
=> Closes drawer after menu selected if narrow

app/elements/app-theme.html
Was the only piece of code using 4 spaces ;)
=> fixing indentation

package.json
npm install wasn't working when behind the http proxy
=> got rid of git://

app/elements/app-theme.html
Ref: https://github.com/PolymerElements/polymer-starter-kit/issues/85
Reviewer: @peterblazejewicz
=> Make desktop-x-large media queries more sensible

app/test/my-greeting-basic.html
Quick followup to an earlier PR. Sorry!
Ref https://github.com/PolymerElements/polymer-starter-kit/pull/81
Ref https://github.com/PolymerElements/polymer-starter-kit/commit/a87c51aa285847a0ab59f57fbf887950bc276982#commitcomment-11444276
=> Followup fix to the tests

gulpfile.js, package.json
Ref https://github.com/PolymerElements/polymer-starter-kit/commit/26073d7d61a54af9c171942f141d08d70137b244
=> Really drop the server configs

app/scripts/app.js
Generally I wouldn't create a PR like this but in boilerplates and starter kits this is
ends up being an inconsistency in not only this codebase but in the codebase of everybody
that uses that specific boilerplate.
Sorry :p
=> Update `app.js` code style

README.md
@arthurevans do you think you might be able to help with a review of the below additions? I know you're not familiar with the Starter Kit, but I'd love to know if any of this makes sense.
=> Add a FAQ section to the README

.bowerrc
=> Drop .bowerrc (Fixes #125)

app/index.html, app/scripts/app.js
reviewer: @sergiotirado @arthurvr
=> Switch to force-narrow (Fixes #132)

app/robots.txt
Their site has been broken for years now.
Ref https://github.com/h5bp/html5-boilerplate/commit/4e5f438e1ea0d7e39179ba5cf799a8d326ba7cc3
=> Fix url in `robots.txt`

app/manifest.json
=> Add missing manifest icon type (closes #219)

bower.json
=>  Bower deps should get latest minor patches

gulpfile.js
For consistence and readability, normalize the casing in comments to sentence-case.  
See https://github.com/google/web-starter-kit/commit/42365d1b7ef9b848dc4b9398534d8802aaf07f1e.
=> Gulpfile: comments in title-case => sentence-case 

README.md, gulpfile.js, package.json
=> Adds support for polybuild (fixes #312)

gulpfile.js
I know it's nitpicky, but it's consistent and more correct ;) 
Ref https://github.com/PolymerElements/polymer-starter-kit/pull/314#discussion_r37340329
=> Casing consistency tweak

gulpfile.js
=> Fix indentation in `gulpfile.js`

app/test/my-list-basic.html
I think this is my 4th PR to this project to fix indentation :P
=> Fix indentation

docs/README.md, docs/add-es2015-support-babel.md
=> Adding an ES2015 recipe.

app/elements/my-greeting/my-greeting.html, app/elements/my-list/my-list.html, app/test/my-greeting-basic.html, app/test/my-list-basic.html, wct.conf.json
=> 🍕 Add polymer imports to default elms

.jshintrc
ref https://github.com/jshint/jshint/issues/438
fixes #352
=> 🍭 Fix jshint strict warning

docs/recipes/README.md, docs/recipes/chrome-dev-editor.md
Implementation of #121 `docs\recipes` for CDE
=> Add docs/recipes for Chrome Dev Editor

app/elements/my-greeting/my-greeting.html, app/elements/my-list/my-list.html
Adds `use strict` to my-greeting.html and my-list.html now that jshint
config is fixed to handle this.
=> Add use strict to elements

docs/polymer-perf.md
Fixing some typos, adding semicolons and some general cleanup.
=> Small docs cleanups

gulpfile.js
Reverts PolymerElements/polymer-starter-kit#365
=> Revert "Fix 'clean' task in gulpfile.js"

gulpfile.js
=> ⭐️ Support external CSS/JS out of the box.

wct.conf.js, wct.conf.json
=> 🍕 Allow for dynamic dynamic project folder.

gulpfile.js
* Fixes #414
* Fixes #364
* Fixes #373
=> 🐬  Remove del race condition

docs/add-es2015-support-babel.md
Still think this should be made more pluggable using the tasks directory so you don't have to mess with the gulpfile itself.
=> optimizeHtmlTask

README.md
Adds Recipes to out of box section or README .  Fixes #449
=> Add Recipes to README

app/styles/shared-styles.html
=> Fix menu not working in FF 38 (fixes #166)

app/styles/app-theme.html
```
.bg {
background: white;
}
```
=> css bloat?

.travis.yml, package.json
=> tests: Lint codebase on every PR

gulpfile.js
Using dist() function helps users change path of dist easily where they want
=> Using dist() to manage path of dist

docs/add-es2015-support-babel.md
Checkout the latest docs for gulp-babel: https://github.com/babel/gulp-babel
=> Babel now requires the ES2015 preset.

app/styles/app-theme.html
Because the layouts are loaded by default, we could use it in the app
theme.
Closes #529
=> Use layout's mixins

.travis.yml, travis-runner.sh
This will cause travis-runner-sh to auto run.  @samccone please review :smile:
=> Add travis-runner-sh to .travis.yml

travis-runner.sh
See http://stackoverflow.com/a/22084103/2403875. Tested on Mac and it worked!  Should now work for travis-ci it uses Ubuntu.
=> Fix sed syntax so it will work with both Mac & Linux

.travis.yml
Also update from Nodejs 4.1 to 4.2 which is LTS version.
=> Add Nodejs 5.1 to travis config

README.md
@addyosmani you cool with me adding some links to the tutorials in the README?
=> Add links to tutorials

README.md, docs/README.md, docs/mobile-chrome-apps.md
follow https://github.com/PolymerElements/polymer-starter-kit/pull/523
=> Add a new recipe for Mobile Chrome Apps

bower.json, gulpfile.js, package.json
Revert 7e4b99 and 967aae
@samccone @chuckh @addyosmani PTAL
=> Fix broken dist. Close #564

docs/mobile-chrome-apps.md
The thumbnail now goes to the video when clicked.
=> Fix thumbnail link in mobile-chrome-apps.md

app/index.html
cleaning up accidental closing tag on meta tag
=> meta tags are self closing

.travis.yml
in an attempt to get the tests passing again...
---
firefox 43 was the issue
=> Lock firefox version down

docs/add-es2015-support-babel.md
Related to https://github.com/PolymerElements/polymer-starter-kit/issues/605
=> Fix busted ES2015 recipe

docs/polymer-perf.md
Changes made:
- Adding the bundle link tag in the page to improve initial load
- Presenting both the initial link tag approach and the `loadElements` approach as separate
- Parameterizing `loadElements` with a path to the bundle and a callback
- Using in-page markup for the splash example instead of innerHTML to improve first paint
@ebidel @samccone PTAL
=> Update perf recipe

docs/chrome-dev-editor.md
=> Update CDE recipe with more info on bower_components

.jscsrc, gulpfile.js, package.json
I can't recall if the caret will pick up a minor rev like this so i upticked the version just in case
=> Rev html-extract and add strip option

app/styles/app-theme.html
Update to the new theme custom properties.
Reference: https://github.com/PolymerElements/polymer-starter-kit/issues/436#issuecomment-163551192
=> Update to the new theme custom properties

app/elements/elements.html, app/elements/my-greeting/my-greeting.html, app/elements/my-list/my-list.html, app/index.html, app/styles/app-theme.html
Fix #570: Remove deprecated /deep/ imports
Now use mixins instead of classes. :tada:
=> Fix #570: Remove deprecated /deep/ imports

README.md
this should allow the demo app to make use of service worker and demonstrate its capabilities
Related to: https://github.com/PolymerElements/polymer-starter-kit/issues/644
=> updated demo link to https

gulpfile.js
=> Close Gh-505. Only do image task on dist

.travis.yml, docs/deploy-to-firebase-pretty-urls.md, docs/firebase.json, travis-runner.sh
Replaces pr #584 and addresses auto deploy part of issue #583.  PTAL @robdodson.
=> Add Auto Deploy to Firebase

docs/deploy-to-github-pages.md
Reference: https://github.com/PolymerElements/polymer-starter-kit/issues/644#issuecomment-170630257.
=> Add HTTPS force to the GH recipe

docs/README.md, docs/deploy-to-google-app-engine.md
Heavily based on https://github.com/ebidel/polymer-gmail/blob/master/app.yaml
Fixes #634
=> Add deploy recipe for gae

travis-runner.sh
Fixes: #654.
Also add only deploy for Node 5.1.
=> Add force https to ghpages auto deploy

gulpfile.js
=> Trim down ensureFiles

gulpfile.js
=> Stop watching changes on bower_componenets

docs/README.md, docs/neon-animated-pages.md
=> New "Add page transitions with neon-animated-pages" recipe

README.md, app/elements/my-list/my-list.html, docs/README.md, docs/add-eslint-support.md, gulpfile.js
[Polymer uses now ESLint](https://github.com/Polymer/polymer/pull/3382) so I´ve created this recipe to use the tool.
The idea of this pull-request is from the comment of @chuckh in the [pull-request 707](https://github.com/PolymerElements/polymer-starter-kit/pull/707#issuecomment-186224704)
=> Create recipe to add lint task with ESLint

app/styles/app-theme.html
This fixes #709 by replacing the hex values with css variables to the colors from paper-styles/color.html.
closes #709
=> Change the primary and accent colors from hex to vars

docs/deploy-to-google-app-engine.md
This pull request is to add additional documentation to the Google App Engine recipe and fixes https://github.com/PolymerElements/polymer-starter-kit/issues/724
=> Update Google App Engine recipe to include http support

docs/deploy-to-google-app-engine.md
- Please note paragraph introduced in #725 is edited to stick out as its content originally suggest it should and minor typos corrected associated with `HTTP` & `HTTPS`. 
- Minor sentence structure tweaks 
- A slightly longer paragraph associated with the new paragraph introduced in #725. 
Based on being a direct PR as a result of #725, the participants of that PR such as @samccone & @johnwhitton should ideally be among the participants of this PR.
=> Add warning about potential pitfalls using HTTP w/ PSK; correct minor typos from PR #725

gulpfile.js
From Polymer 1.1, the elements hasn't .css files.
=> Remove unused task and watch

docs/add-es2015-support-babel.md
@samccone Here you go
Relates to #625
=> Adding docs for update Vulcanize to get babel translated files

docs/add-eslint-support.md
Reference: https://github.com/PolymerElements/polymer-starter-kit/pull/711
=> Remove elements task in add-eslint-support.md

docs/add-es2015-support-babel.md
Fix linting error
Change replace statements to corresponds to last code snippets
=> Improve ES2015 documentation to just copy and paste changes

.travis.yml, app/index.html, app/styles/shared-styles.html
=> Add a selected menu item background color

README.md, app/elements/my-greeting/my-greeting.html, app/elements/routing.html, app/index.html, app/styles/main.css
=> Fix header flicker behavior

docs/neon-animated-pages.md
Fixed two typos. Thanks for the 1.3.0 release :tada:
=> Fix typos in neon animated pages guide

app/elements/routing.html, app/index.html, app/styles/main.css
=> Improve focus managment

docs/neon-animated-pages.md
Update recipe to handle focus with `neon-animatable`.
=> Should fix #742

src/psk-app/psk-app.html
Add missing paper-styles/color.html, used in :host --paper-indigo-500
=> Add missing paper-styles/color.html

src/psk-app/psk-app.html, src/psk-pages/psk-page-404.html
Reference: https://github.com/PolymerElements/polymer-starter-kit/pull/786#issuecomment-208481801
=> Update 404 page

.travis.yml
Reference: https://github.com/Polymer/polymer/pull/3510
=> Enabling caching of node_modules on Travis

.travis.yml
Reverts PolymerElements/polymer-starter-kit#775
=> Revert "Enabling caching of node_modules on Travis"

.travis.yml
Reference: https://github.com/PolymerElements/polymer-starter-kit/pull/807
=> Reenable caching of node_modules

index.html, src/app-icons/app-icons.html, src/psk-app/psk-app.html, src/psk-page-404/psk-page-404.html, src/psk-page-art/psk-page-art.html, src/psk-page-design/psk-page-design.html, src/psk-page-film/psk-page-film.html, src/psk-page-home/psk-page-home.html, src/styles/shared-styles.html
Update `bower_components` path to support `polytool serve`.
The new `generator-polymer-init` already use these paths: https://github.com/PolymerLabs/generator-polymer-init/blob/master/generators/app/templates/application/index.html
=> Update bower_components path to support polytool serve

src/psk-app/psk-app.html, src/psk-page-404/psk-page-404.html
Now that latest `polyserve` / `polytool serve` support pretty urls let’s
make it the default approach.
=> Change to pretty urls

index.html, src/styles/shared-styles.html
Minor typo changes:
webcomponents > Web Components
WCR > WebComponentsReady
=> Minor typo changes

bower.json
Update Polymer version to 1.4
Update Polymer Elements version
=> Update Polymer version : 1.4

src/psk-app/psk-app.html
=>  CSS reduction and add header effects

bower.json, src/psk-app/psk-app.html
Change app-layout to PolymerElements from PolymerLabs
=> Change carbon-route to app-route

src/test/index.html, src/test/psk-page-home.html, wct.conf.js
Addresses item 1 for issue #835
=> Add test stub

gulpfile.js, service-worker.js, test/index.html, test/psk-page-home.html, wct.conf.js
Now all the files have the same license.
=> Consistent licenses in all files

bower.json
As this is a "new" project, update dependencies to the latest minor versions.
=> Update dependencies versions

src/psk-app.html
Reference: https://github.com/PolymerElements/app-layout/releases/tag/v0.10.0
=> Fix app-layout breaking change: title > main-title

src/psk-app.html
=> Add pprl 404 handling

src/psk-app.html
Updated method declaration syntax for consistency.
=> refactor(psk-app): Adhere to polymer's method declaration syntax

polymer.json
=> Add webcomponentsjs as includeDependencies

src/my-view1.html, src/my-view2.html, src/my-view3.html, src/my-view404.html, src/shared-styles.html
Add shared styles to app-drawer-migration branch. @robdodson PTAL.
=> Add shared styles

README.md
Short and avoid comments in the 'terminal' code as the 'Start the development server' step
=> Update build commands

polymer.json
=> Include manifest.json to includeDependencies

polymer.json
Basically the same as https://github.com/PolymerElements/polymer-starter-kit/pull/900
=> Add manifest.json to polymer.json

README.md
=> Readme for deprecation

index.html, src/my-view404.html, sw-precache-config.js
=> Change to relative paths

.travis.yml
as Selenium - Firefox issue is now fixed SeleniumHQ/selenium#2110.
=> Set firefox to latest for travis

src/my-app.html, src/my-icons.html
=> Give iconset a unique name

index.html, src/my-view404.html, sw-precache-config.js
I made these separate commits for now so  I can easily revert any of them. I will squash before the merge if requested.
The following items were addressed:
- Updated webcomponent polyfill check to use ES6.
- Updated polymer to be even more lazy using the `lazyLoad: max` and `useNativeCSSProperties: true`.
- Updated the app import to be asynchronous. (Noticed this on a few Google projects)
- Updated the webcomponent polyfill check to be at the bottom of the body. (Noticed this on a few Google projects)
Happy to address any feedback! Thanks for the awesome app starting point!
=> Update webcomponent polyfill check to use ES6

index.html, sw-precache-config.js
See discussion here https://github.com/PolymerElements/polymer-starter-kit/pull/940#issuecomment-261645920
=> Back out #940

test/my-view1.html
Quick fix to make the dummy test pass
=> Fix dummy test for 2.0-preview

bower.json
Oops! I forget remove the dependency.
=> Remove unused dependency

.travis.yml
The same as https://github.com/PolymerElements/polymer-starter-kit/pull/1003
=> Remove Node v4 support

index.html
Display a message for users with javascript disabled
=> New: Add noscript message

polymer.json
Fix #975
First, we need wait to the Polymer CLI v0.18.0 release:
https://github.com/Polymer/polymer-cli/releases
=> Rename to sources and extraDependencies

.travis.yml, package.json
Now will be easy add more linters like `polymer lint` or `stylelint`.
=> Update lint setup

package.json
Seems like all lint errors were fixed by @justinfagnani. It would be a shame not to go ahead and lint
=> [2.0] New: Add polymer lint to lint script

index.html, polymer.json, src/my-app.html
=> [master/polymer-1] Simpler differential serving & non-root-paths

src/my-app.html
Fix regex according to https://github.com/PolymerElements/polymer-starter-kit/pull/1031#issuecomment-307143188.
=> Fix url-space-regex according to #1031

polymer.json
=> Remove webcomponentsjs/gulpfile.js as extraDependency
