Polymer/polymer-starter-kit

app/elements/app-theme.html
Currently the paper material has no right padding which causes content to touch the edges of the paper on the right side:
This fixes that. Thanks!
=> Adds equal left and right padding to paper-material

app/elements/app-theme.html
Otherwise {{appTitle}} is still visible when you scroll and flatten the waterfall-tall toolbar
=> fixes #mainToolbar padding

bower.json, package.json
Marks the NPM and Bower package private, and as a result removes all needless properties. This prevents people from accidentally publishing it to the registry.
Also, keeping those properties up to date is a waste of time when you're not planning to publish it and only are planning to use those for devDependencies (which out of the box is the case). There's no deal with publishing a whole site to bower/npm so I guess this is the right choice to make.
Fix https://github.com/PolymerElements/polymer-starter-kit/issues/102
Ref https://github.com/PolymerElements/polymer-starter-kit/commit/1076cd7fba3743aec12f98ddd3fec69a2aa691a5
=> Mark packages as private

app/elements/app-theme.html, app/index.html
reviewer: @chuckh (if you have time)
This set of changes attempts to update the hamburger menu (and application name) positioning to be closer to the Material spec.
Spec:
Layout:
@kenchris is this closer to what you were after based on your reading of the spec? I think you were suggesting 20 was the right distance between the icon and title, however if it was 56px (your earlier number), that's easy enough to update to. 
It also includes several changes meant to improve the paper-header-panel/scroll behaviour of the layout, especially when there's more content than one card inside the page.
=> Layout and hamburger-menu improvements

README.md, bower.json
This is required for Polymer 1.1.0 to install. Also for Selenium to
work when running gulp test:local you have to update to Java 7 or
later. Updates readme.md for requirement.
@addyosmani please review.
=> Update dependency for Polymer 1.1.0

app/elements/my-greeting/my-greeting.html
This looked like unused and added by accident in https://github.com/PolymerElements/polymer-starter-kit/commit/98a7e3c37f824386b8b0028d6fb3014df0844f90.
=> Remove an accidentally added word

README.md, app/elements/elements.html, app/elements/my-greeting/my-greeting.html, app/index.html, app/styles/app-theme.html, app/styles/shared-styles.html
Add the new Polymer 1.1.0 share styles approach. Addresses #267.
=> Add shared styles

gulpfile.js
I think we don't need to check extension of css anymore. cause of #6
=> Remove css extension checking

.jshintrc
JS6 support is now handled as part of of a recipe. See #333.
=> Remove ES6 support from JSHint.

gulpfile.js
Currently gulpfile.js is not being checked with jshint. This commit fixes that.
=> Check gulpfile.js with jshint

gulpfile.js
Task `clean` does not return, thus breaking default gulp task.
Added a `return` statement to fix it.
=> Fix 'clean' task in gulpfile.js

gulpfile.js
Being convinced during the polymer summit by ebidel's talk to try es6
with polymer, I followed docs/add-es2015-support-babel.md.
Adding jshint + js tasks triggers a double refresh request, but only the first
one is executed by the browser, and so, it runs most of the time previous
version of the code (transpiled by babel during last refresh). There is a thus
a race between the first browser refresh request and the transpilation of the
code.
gulp serve gives, when saving a modified elements/**/*.html file:
[18:13:42] Starting 'js'...
[18:13:42] Starting 'jshint'...
[PSK] Reloading Browsers...
[18:13:44] Finished 'jshint' after 1.18 s
[18:13:44] Finished 'js' after 1.76 s
[PSK] Reloading Browsers...
This is due to the jshint task asking explicitely for a one time refresh.
Removing it fixes …
=> Remove double page refresh when adding jshint + js tasks

README.md, gulpfile.js, package.json
Per the discussion on our group thread with the team, reverting back to Vulcanize for now.
Polybuild and the transitive dependencies it has currently break in a number of different scenarios, spanning breakage of apps using Firebase in [polyclean](https://github.com/PolymerLabs/polyclean/issues/4) through to issues with how it treats Service Worker scripts, [ES2015](https://github.com/PolymerElements/polymer-starter-kit/issues/369) and so forth. We're confident these issues can be resolved upstream but wish to restore build stability to PSK using the same setup we did in previous releases. 
r @samccone @chuckh
=> Revert back to using Vulcanize over Polybuild

README.md
Hi, I've updated the attribute name in the section about how to enable service worker support. 
The new version of `platinum-sw-register` use a different name. Now is `cache-config-file` but in the current README file says `precache-file` .
Regards.
=> fix(README.md): change the attribute name of the cache file

app/index.html
Following the suggestion from the Polymer docs.
>"...tap should be used instead of click for the most reliable cross-platform results."
>https://www.polymer-project.org/1.0/docs/devguide/events.html#gestures
=> Updated "on-click" to "on-tap"

app/scripts/app.js
This PR switches `app.js` over to using Polymer's Shady DOM API for querying the document (https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#dom-api). This should preserve Shadow boundaries. I believe moving forward if you're querying the DOM you'll always want to use  `Polymer.dom` methods.
This should fix https://github.com/PolymerElements/polymer-starter-kit/issues/379 as it's now querying the Light DOM `paper-scroll-header-panel` and using its API to scroll, instead of the `mainContainer` element which should be hidden by Shadow DOM.
@samccone @chuckh @addyosmani PTAL
=> Use Polymer.dom in app.js. Fixes Gh-379

gulpfile.js
This is more of a stop-gap than anything, but should alleviate some of the issues we saw over in #422. r: @chuckh 
I haven't been able to understand why SVG files aren't being copied over. We're following the same pattern used in Web Starter Kit and the gulp-imagemin docs.
=> Disable caching for imagemin task (#422)

gulpfile.js
Fixed #478.
The issue was introduced with https://github.com/PolymerElements/polymer-starter-kit/commit/0dc4d13b2495032efb04424f3ae887dac801b1ad for what I can see.
=> Only run jshint once

app/elements/my-greeting/my-greeting.html, app/index.html
As of Polymer 1.2 these span tags are not necessary anymore and we should provide a good example for users of this starter kit.
=> Remove extraneous `span` tags

gulpfile.js, package.json
As the `vulcanize` process inlines the JS and CSS for elements, the resulting `elements.vulcanized.html` contains several hundred KB of empty space. By using gulp-minify-inline on the vulcanized file, the size goes from 447K down to around 267K for the default install. Even with gzipped calls, this can be quite a bit of pageload reduced.
=> Use gulp-minify-inline to minimize the elements.vulcanized.html after generation

app/scripts/app.js
Before scaleMiddle was always being set to 0.5 (maxMiddleScale). Fixes
#491
=> Fixes app name scale calc (Fixes #491)

docs/polymer-perf.md
Just fixing what appears to be a typo as I was playing with the example code.
=> Typo fix - example missing quotes

.travis.yml, app/test/my-greeting-basic.html, app/test/my-list-basic.html, bower.json, package.json
`sudo: false` for the new docker-based build containers (much faster)
Install latest chrome and firefox 42 (workaround travis-ci/travis-ci#5082, broken `firefox: latest`)
=> Add firefox 42 and Chrome stable to travis tests

app/test/index.html, app/test/my-greeting-basic.html, app/test/my-list-basic.html
r: @samccone 
Test output on Mac:
```
Installing and starting Selenium server for local browsers
Selenium server running on port 50312
Web server running on port 2000 and serving from /Users/addyo/projects/io-workspace/polymer-starter-kit
safari 9.0.1             Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=3
safari 9.0.1             Tests passed
firefox 42               Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=2
chrome 47                Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.html?cli_browser_id=0
chrome 49                Beginning tests via http://localhost:2000/components/polymer-starter-kit/generated-index.h …
```
=> Switch tests to webcomponents-lite (fixes #473)

travis-runner.sh
Remove extra space in first sed command. Hopefully will fix error `sed: -e expression #1, char 1: unknown command: `.'` for travis-ci build process.
=> Remove extra space in travis-runner.sh 

README.md
If you would copy-paste the HTML code in the README.md, it would generate a 404 as `precache.json` was not found.
In `index.html`, this is `cache-config.json` which does not 404.
=> Fix cache-config-file in README

bower.json
Fixes issues #561, #559, #557 by reverting back to iron-flex-layout
version 1.2.1, version 1.2.2 causes this problem. Still need to find long term fix.
Fixes layout issues for Chrome, Firefox and Safari, but not IE 11 or
Edge (#550).
r: @addyosmani / @samccone
=> Fix menu layout issues

app/index.html
If you don't add the `{{baseUrl}}`, the href paths are wrong after you go to a specific user's page - i.e. when on `http://localhost:5000/users/Addy`, the **Users** link will take you to `http://localhost:5000/users/users`
=> Update href paths in index.html

README.md
Proposing this as an alternative to https://github.com/PolymerElements/polymer-starter-kit/pull/555
Hopefully improves https://github.com/PolymerElements/polymer-starter-kit/issues/544
Addy has added a write up to the release notes, and hopefully adding this warning to the README also makes it very clear that the user should be on the lookout for those dotfiles. I would much prefer we try to go this route and see if folks still have problems vs. adding new code to the gulpfile to check for missing stuff.
`<tangent>`
I've been feeling that the gulpfile is getting really large and difficult for users to modify and, equally important, for us to safely maintain. https://github.com/PolymerElements/polymer-starter-kit/pull/568 is an attempt to correct some of this. I'd love if we could do some …
=> Add dotfile warning to readme

docs/deploy-to-firebase-pretty-urls.md
`hashbang: false` is the default for `page.js` so you can just remove it entirely and call `page()`. @chuckh PTAL
=> Small tweak to Firebase recipe

gulpfile.js
=> Correct Travis CI spelling

.bowerrc, README.md, app/index.html, app/test/index.html, app/test/my-greeting-basic.html, app/test/my-list-basic.html, docs/add-es2015-support-babel.md, docs/mobile-chrome-apps.md, gulpfile.js
Fixes #562
Should help #512
- Move bower_components into app dir
- Because we mount the bower_components directory it makes vulcanizing totally insane (hence all the weird stuff where we copied over all of bower_components and vulcanized in the dist directory, instead of vulcanizing in app and writing the output to dist. Doing it this way also screws up tools like `web-component-shards` and Superstatic (as mentioned in #512). I realize it's [a Yeoman convention](http://yeoman.io/blog/bower_components-in-project-root.html) to have bower_components outside of app, but for Polymer projects that makes life very difficult.
- Remove code to rename `elements.html` to `elements.vulcanized.html`. Instead, `dist/elements/elements.html` is just the vulcanized version of `app/elements/elements.html` …
=> Move bower_components. Make vulcanize easier

gulpfile.js, tasks/ensure-files.js
via https://github.com/PolymerElements/polymer-starter-kit/pull/555
fixes #544
R @robdodson
=> Add friendly error message for missing dotfiles

.jscsrc
JSCS is barking at a lot of our users, many of whom may be unfamiliar with it. This relaxes JSCS rules around indentation a bit while we sort out the best way to deal with extracted JS
@samccone PTAL
=> Relax jscs indentation rules

app/styles/app-theme.html
Addresses a small quirk referenced in #279.
Although the `::after` element uses `background: currentcolor` it produces a weird flicker (I guess something to do with the style shimmer) so I'm setting its value as well.
=> Use paper-menu mixin for selected styles. Fixes Gh-279

gulpfile.js
Ignores .DS_Store files in gulp copy. Per this issue: https://github.com/PolymerElements/polymer-starter-kit/issues/464
=> Ignore .DS_Store files in gulp copy. Fixes Gh-464

bower.json
paper-menu 1.2.1 menu highlight works now. Fixes #515. I tested on Mac: Chrome 47, Firefox 43, Safari 9.0.1, Windows 10: Edge and IE11, iOS: Safari 9.2 all works fine.
=> Revert back to using current paper-menu

README.md
The link in the README currently points to `https://polymer-project.org` which generates and error:
```
curl -I https://polymer-project.org/
curl: (35) Encountered end of file
```
The www version `https://www.polymer-project.org` is not a 20x/30x but the site is reachable
```
curl -I https://www.polymer-project.org/
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: text/html; charset=UTF-8
Content-Length: 188
Date: Tue, 22 Dec 2015 18:41:03 GMT
Server: Google Frontend
Alt-Svc: quic=":443"; ma=604800; v="30,29,28,27,26,25"
```
=> Update link in REAME from https://www.polymer-project.org

docs/deploy-to-firebase-pretty-urls.md
With the travis-ci auto deploy to firebase we put `<base href="/">`
above `` It seems to work fine.
=> Improve firebase doc fixes #670

docs/deploy-to-google-app-engine.md
These `skip_files` are unneeded because the deploy.sh uses the `dist` folder.
=> Remove unneeded skip_files in the GAE deploy recipe

gulpfile.js
After removing LINT
gulp.watch(['app/{scripts,elements}/**/{*.js,*.html}'], ['lint']);
There's no watching for changes in scripts directory.
This is my temporary fix, before You implement LINT.
=> GULP SERVE - Watch on scripts directory changes

app/styles/app-theme.html
The main toolbar was show black text and icons, instead of white.
See https://polymerelements.github.io/polymer-starter-kit/ and look at
title text.
=> Set Main Toolbar Color to White

app/styles/app-theme.html
Fixed upstream in paper-toolbar to default to white again.  See
paper-toolbar commit:
https://github.com/PolymerElements/paper-toolbar/commit/1f8cc8338220d62f
354b1ab12ae2829222f60a67.  This is part of paper-toolbar release v1.1.4.
=> Remove #mainToolBar color

package.json
According to the documentation the node version should be at or above 0.12.x.
This just updates the `package.json` accordingly since building with `0.10.x` does not work.
=> Update required node version in package.json

app/elements/my-greeting/my-greeting.html, app/index.html
I've changed the levels of the headers in the examples due to accessibility. I think is better to use a level 1 header for the greetings component to not confuse the users in the examples.
I've used tools like [Claws](https://addons.mozilla.org/es/firefox/addon/claws/) or [Fangs](https://addons.mozilla.org/es/firefox/addon/fangs-screen-reader-emulator/) to review the headers levels.
=> Change headers hierarchy to improve accessibility

app/elements/my-greeting/my-greeting.html
An small and quick fix to improve the accessibility of the my-greeting component. It replaces the span element with a label.
I forgot to include this change in the pull request of yesterday. Sorry for that.
=> Associate a label with the input control to improve accessibility

app/test/my-greeting-basic.html
Test broke when `<h2 class="page-title">{{greeting}}</h2>`  was changed to `<h1 class="page-title">{{greeting}}</h1>`.  See:
https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/elements/my-greeting/my-greeting.html#L27
@robdodson PTAL.
=> Fixes Selenium tests failing #710

docs/add-eslint-support.md
`node_modules/ ` and `bower_components` will be ignored by default like described in their [documentation](http://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories).
Instead, ignoring the `dist/` makes sense because other than in the gulp task where we explictly define `app/*` a plugin in an editor has it's entry point in the root folder.
=> ignore dist folder

.travis.yml, gulpfile.js, package.json
This should fix node 0.10 support (#699) since it includes a Promise polyfill required by at least PostCSS.
=> Fix node 0.10 support

README.md
Expands on #733, related to issue #95.
Since we have added a section on triggering a web app install banner, I feel we should mention this common pitfall and point the users in the right directions.
=> Mention caching of start_url when opening from home screen

README.md, docs/deploy-to-github-pages.md
This change reduces confusion about using backslashes or not in the URL and is generally more helpful to new comers.
=> Fixes small confusion in documentation regarding requiring backslashes

app/index.html
It was recently set to -1 by mistake.
=> Fix the user-info page paper-material elevation

app/index.html
The default responsive width to hide the paper-drawer-panel is an uncomfortable 600px -- let's increase it to 840px, a value consistent with media queries found in the PSK.
=> Responsively hide drawer panel @840px

.gitignore
Until we decide not to use `gulp` with PSK2 we need to ignore `dist`.
Until we change our method to deploy to Github Pages we will still want
`.tmp` and `.publish/`
=> PSK2 update .gitignore for deploy

src/psk-app/psk-app.html
This PR adds a 404 default message when a specific page could not be found. It uses the recently added property `fallback-selection` (ref: https://github.com/PolymerElements/iron-selector/pull/117)
1. Open the PSK in your browser
* Modify the url by replacing `art` with a non-existing page (for example `asdf`)
* Observe the 404 message is displayed and the URL has been changed to `/#/404`
The last step is due to the two-way binding on the `selected` property. If you do not want to modify the url (e.g. keep the url at `/asdf`) I can revert back to one-way binding.
=> Add 404 section to iron-pages with fallback-selection

.travis.yml
Trusty has gcc 4.8, drop ubuntu-toolchain-r-test ppa
Fixes #794
=> Migrate to Travis trusty

.travis.yml
Trusty has gcc 4.8, drop ubuntu-toolchain-r-test ppa.  This matches
PSK1 master. Based on @azakus changes to PSK1.
=> Migrate PSK2 to Travis trusty

index.html
Based on https://gist.github.com/ebidel/1d5ede1e35b6f426a2a7
@justinfagnani confirmed that this should be compatible with the CLI as it just uses `polyserve`.
=> Lazy load polyfill if browser does not support native webcomponents

index.html, src/psk-app/psk-app.html, src/psk-page-art/psk-page-art.html, src/psk-page-design/psk-page-design.html, src/psk-page-film/psk-page-film.html, src/psk-page-home/psk-page-home.html
- Add `sample-content` taken from app-layout examples
- Switch to greyscale colors
- Remove unused styles
- Add default `lang` to make a11y audit tools happy
=> Sample content for all pages and style cleanup

src/psk-app/psk-app.html
app-scrollpos-control is a manager for saving and restoring the scroll position when multiple pages are sharing the same document scroller.
=> Add Scroll Position Control

index.html, src/psk-page-art/psk-page-art.html, src/psk-page-design/psk-page-design.html, src/psk-page-film/psk-page-film.html, src/psk-page-home/psk-page-home.html, src/styles/shared-styles.html
Add page title to each page. When using PSK2 on mobile you can
determine which page you are on without looking at url or opening menu.
Also made Design page content size 2 to have one short page for
testing.
=> Add Page Titles

.travis.yml
This is a resubmission of #775 . The original changes were reverted in #793 . However, the build failed due to problems with installing Chrome, as fixed in #794 .
The failing build log: https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/122964581#L149
=> Reenable caching of node_modules

docs/add-es2015-support-babel.md, docs/add-eslint-support.md, gulpfile.js, package.json
- update gulp-useref to version 3 (it changes [how to use the assets](https://github.com/jonkemp/gulp-useref))
- new 'build' task to replace 'html' task. This new task runs 'images' and 'fonts' and after that, it searchs for the assets in the html files and optimize them.
This way I think that 'default' task is more clear.
=> New 'build' task to replace current 'html' task

src/psk-app/psk-app.html, src/styles/shared-styles.html
Creates a simplified mobile header as discussed here: https://github.com/PolymerElements/polymer-starter-kit/pull/825
=> Simplify header

.travis.yml
Added `--no-recursion` so Travis CI will pass.  This change will stop
`polymer lint` from linting bower_components.
=> Fix travis linting

app/index.html
This part of the MD specifications says that you shouldn't have dismiss buttons: https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage
Continuing PR #865
I tested it and it works. As far as I know there are no toasts without timeout in PSK.
=> Change made to confirm to MD specs

package.json
Polymer CLI already use `>=4.0`: [Polymer/polymer-cli/package.json#L7](https://github.com/Polymer/polymer-cli/blob/master/package.json#L7)
=> Update minimum Node version (like polymer-cli)

bower.json
Speeds up `polymer build` process from 58 seconds to 18 seconds. Will also speed deploying to http2 servers since unused components will not be copied to the server.
=> Install only used components

.travis.yml
Reverts back from Firebox 47 so tests will pass. In Firefox 47 broke
web driver setup.
=> Change travis config to use firebox 46

gulpfile.js, package.json, polymer.json, src/psk-page-404.html, src/psk-page-about.html, src/psk-page-home.html, src/sample-content.html
Polymer-build has released version 0.3.0, which breaks the current gulpfile.js and sample-content running from build folders:
**The PR does:**
- Update gulp file for Polymer-build 0.3.0
- Add sample-content to src folder
- Add clean task to gulp file
- NOTE: imagemin is not working yet! Not sure why.
See https://github.com/Polymer/polymer-build/blob/master/test/test-project/gulpfile.js for example gulpfile for version 0.3.0.
@robdodson @abdonrd @justinfagnani PTAL.  See https://github.com/PolymerElements/polymer-starter-kit/compare/psk2...polymer-build-030?expand=1#diff-b9e12334e9eafd8341a6107dd98510c9R62
=> Polymer build 030

src/my-app.html
Hi,
The title says it all!
It's only has minor modifications, but with great gains.
I gave an ID to the drawer so that I could refer to it with `this.$.drawer`. I hope that's accetable!
Merc.
=> Drawer will hide on page change, unless drawer is persistent

package.json
Add .gitignore as ignore-path to ESLint to avoid lint the `build` folder.
Also, remove the `exit 0;` to avoid the false positive.
=> Add .gitignore as ignore-path to ESLint

.eslintrc.json, bower.json, index.html, polymer.json, src/my-app.html, src/my-view1.html, src/my-view2.html, src/my-view3.html, src/my-view404.html, src/shared-styles.html, sw-precache-config.js, test/index.html, test/my-view1.html
---
- Merges into a new `2.0-preview` branch instead of `master`.
- Tested with `polymer serve`, `polymer lint`, `polymer build` & `polymer test`
/cc @robdodson @justinfagnani
=> Convert psk to use polymer 2.0

README.md
if a user attempts to follow the documented setup instructions without bower installed they will receive an error
```
⇒  polymer init starter-kit
info:    Running template polymer-init-starter-kit:app...
info:    Downloading latest release of PolymerElements/polymer-starter-kit
info:    Unpacking template files
info:    Finished writing template files
I'm all done. Running bower install for you to install the required dependencies. If this fails, try running the command yourself.
module.js:472
throw err;
^
Error: Cannot find module 'internal/fs'
at Function.Module._resolveFilename (module.js:470:15)
at Function.Module._load (module.js:418:25)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at evalmachine.<anonymous>:18:20
at Object.<anonymous> …
```
=> update readme setup instructions to include bower requirement

.travis.yml, package.json
The Polymer CLI supports automatic cloning of the Polymer Starter Kit into an empty directory via the `init` command. However, we occasionally get reports when different CLI commands stop working on the PSK and other templates. 
This PR cleans up the project's travis.yml file a bit, and adds a simple test for all relevant CLI commands  (currently this is just `polymer build`, but when the `polymer lint` command is ready we can add that as well).
There is a sibling PR to add these to the `master` Polymer 1.0 branch as well: https://github.com/PolymerElements/polymer-starter-kit/pull/986
/cc @robdodson @abdonrd @rictic
=> update travis & package.json to add cli integration tests

.travis.yml
Node v5 is no longer supported by Polymer or even the Node team. Lets change travis to test LTS & the latest version as per our support policy.
=> travis: remove node v5, add node latest

index.html, manifest.json, src/my-app.html, src/my-view404.html
(PSK 3.0/2.0-preview) Implements relative paths as talked about on #981 without using `use-hash-as-path`.
Uses a `<base>` tag with Polymer's `rootPath`.
Here's a live preview built using `polymer build`, and using a pretty generic `.htaccess` for routing:
[PSK on non-root directory](https://silverlinkz.net/_test/polymer/2.0-relative-starter-kit/)
Basically functions the same as current PSK, but much easier to use on subdirectories by simple changing the `<base>`  tag `href`, and having the routes automatically change accordingly.
PS: This method can also be used for PSK 2.0 after `Polymer#1.9.0` lands with backport for `rootPath`.
=> Change PSK 3.0 / 2.0-preview to use relative paths for subdirectory deployment

.travis.yml
The Polymer CLI removes Node v4 support.
>Remove Node v4 support: Node v4 is no longer in Active LTS, so as per the Polymer Tools Node.js Support Policy the Polymer CLI will not support Node v4. Please update to Node v6 or later to continue using the latest verisons of Polymer tooling.
[Polymer CLI - CHANGELOG.md v0.18.0 [04-13-2017]](https://github.com/Polymer/polymer-cli/blob/master/CHANGELOG.md#v0180-04-13-2017)
=> Remove Node v4 support

src/my-app.html
So it turns out that `new URL(...)` isn't supported on IE11, this fix uses the same method on supported browsers, but uses a regex on unsupported browsers.
I wasn't sure if I should just change it to the regex, so for now I kept both with a check for compatibility and moved it all to a computed function to clean it up a bit. This also brings it in line with the pattern used on the tentative Polymer 1 PSK changes. (Will update #master PR with fix after this is finalized.)
If there's a cleaner way to do this, please lmk!
Fixes #1020
=> Add regex for use with IE11 instead of URL()

bower.json, index.html, manifest.json, src/my-app.html, src/my-view404.html, sw-precache-config.js
1. Since `created` is called too early, and `ready` too late, ~~uses an observer to set `rootPattern`.~~ **Now uses a computed property**
1. Since Polymer v1 rewrites paths based on import path it requires `rootPath` bindings for `view` links. (Also works in Polymer 2, but not necessary.) **`rootPath` bindings will also be added to `2.0-preview`**
1. ~~Update Polymer dependency to `1.9.0` for `rootPath` support.~~ **Already done on master**
Due to the differences in rewriting of paths I'm not sure where this fits in continuity between PSK 2.0 and PSK 3.0, ease of use for new users, and ease of use when deploying to a subdirectory.
[Simple Build](https://silverlinkz.net/_test/polymer/relative-starter-kit/)
[Bundled & Minified Build](https://silverlinkz.net/_test/polymer/relative-starter-kit …
=> Use relative paths with Polymer v1 Starter Kit

README.md
Now the `polymer serve` use the http://127.0.0.1:8081 as default.
=> Update the default serve URL

index.html, polymer.json, src/my-app.html
This PR, based on @arthurevans's comments on #1008, is a simpler implementation of support for differential serving and non-root-path deployments.
The key difference is that we set `Polymer.rootPath` to a server-relative path with a leading slash, instead of mimicking its "natural" form (a full URL). We default to `/`, which works for differential serving and for standard, single-build deployments from the server root. For non-root-path deployments, devs will manually edit it to specify the path from which they'll serve (e.g. `/my-app/`).
This eliminates the need for the computed `rootPattern` property, since that property was just massaging `rootPath` into the form that we're now using directly.
Also: added `url-space-regex` property to `<app-location>` to filter out URL changes not …
=> Simpler support for differential serving, non-root-path deployments

src/my-app.html
I think this had to be during the preview, because now it's never `undefined `.
Was added by @FredKSchott at #967.
=> Remove unneeded check

sw-precache-config.js
As @frankiefu recommended here: https://github.com/Polymer/news/pull/141#discussion_r141770890
Also, add images to `staticFileGlobs`.
=> Cache the polyfills in runtimeCaching

src/my-app.html
From #1071.
Lighthouse best practices from 92 to 100! 🎉 
***
Hosted in Firebase. Preset: `es5-bundled`.
> **Lighthouse Report**
> 
> Results for: https://psk-demo-6e320.firebaseapp.com
> Report: https://builder-dot-lighthouse-ci.appspot.com/report.1508442363680.html
> 
> | Category  | Score |
> | ------------- | ------------- |
> | Progressive Web App | 100 |
> | Performance | 95 |
> | Accessibility | 100 |
> | Best Practices | 100 |
> 
> _Tested with Lighthouse version: 2.3.0_
=> Enable set passive touch gestures

polymer.json
The polyfill bundles have moved into `/bundles`.
=> [3.0-preview] Update polymer.json for webcomponentsjs changes.

README.md
This lets users find the older Polycast video and migration blog post. Fixes #1099.
=> [3.0-preview] Add a link to the old README
